apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: development-deployment-svc
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev-app
  type: LoadBalancer
status:
  loadBalancer: {}
