apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: production-deployment-svc
  namespace: prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: production-app
  type: LoadBalancer
status:
  loadBalancer: {}
